### ISSUE TITLE
Filename too long

### ISSUE THREAD

**Issue by hustf** [johnmyleswhite/Vega.jl#96]
When trying to install this package for the first time, I get the following message:

System: Windows 10 64 bit, Julia 0.4.2
Package directory:
    C:\Users\F\.julia\v0.4

´´´´
INFO: Installing Vega v0.6.0
fatal: cannot create directory at 'assets/bower_components/vega/node_modules/bow
er/node_modules/update-notifier/node_modules/latest-version/node_modules/package
-json/node_modules/got/node_modules/duplexify/node_modules/end-of-stream/node_mo
dules/once/node_modules': Filename too long

**Comment by randyzwitch** [comment]
Can you try `Pkg.checkout("Vega")` and tell me if it works? I saw this error in the AppVeyour tests and I think I fixed it on master, but since I don't use Windows I haven't tagged a new version yet.

**Comment by hustf** [comment]
Wow, that was quick! 
I added the package by modifying the REQUIRE file. After removing it from REQUIRE and also deling the folder on disk, Pkg.checkout("Vega") returns "Vega is not a git repo".  Pkg.rm("Vega") returns "Removing Vega (unregistered)". Well, well.

So my package manager is a bit confused now, and I'm running Pkg.update. If Pkg.checkout still doesn't work, would you like me to use git directly, Pkg.checkout or Pkg.clone?

**Comment by randyzwitch** [comment]
It sounds like your directory might be mangled beyond easy repair. It's probably easiest to delete the entire v0.4 folder, then use Pkg.add() to reinstall your packages.

Once you do that, Pkg.checkout("Vega") should work.

**Comment by hustf** [comment]
Quite possible. I'm exploring many different packages simultaneously. Probably not the best of ideas. But this may take some time and the package is already broken on Windows so don't let this refrain you from tagging...

**Comment by hustf** [comment]
On a clean install of 0.4.2 on Windows 10:


```
1)  Pkg.checkout("Vega") ->  "Vega is not a git repo".
2)  Pkg.add("Vega") -> failed process, referring Vega 0.6.0.
3) Pkg.checkout("Vega")-> Vega is dirty, bailing
4) Pkg.rm("Vega") -> Removing Vega (unregistered)
5)  Pkg.checkout("Vega") ->  "Vega is not a git repo".
6) Pkg.clone("Vega")
7) Pkg.checkout("BinDeps") (currently necessary on Windows Ju 0.4.2)
8) using Vega -> Precompiling Vega.
9) Pkg.test("Vega") - > Computing dependencies -> Cloning Conda, PyCall, RDatasets-> Building PyCall->No system wide Python->using the Python distribution in the Conda package -> Get-process: Cannot find a process with the name "Outlook". Verify the process name and call the cmdlet again. -> Downloading miniconda installer....
```

Frankly, seeing "Outlook" being called is quite disturbing. I luckily don't have Outlook, but what is going on here? I broke off the build process at this point.

**Comment by randyzwitch** [comment]
Did you delete your `.julia\v0.4` also, or did you just do a clean install of Julia? It's really the deleting of the packages folder that likely needs to happen. When you delete that folder, then do `Pkg.add("Vega")`, METADATA will be re-downloaded from GitHub and everything should work fine.

In terms of the actual errors you are seeing from above, the cop-out answer is that `PyCall.jl/Conda.jl` are causing the issue, not Vega itself. While I highly doubt they are calling Microsoft Outlook, I can't speak to what's actually happening.

This run of AppVeyor suggests everything should work on 64-bit Windows:

https://ci.appveyor.com/project/randyzwitch/vega-jl/build/job/uqpml06iq0cf2fbe

So I'm not really sure what the next step is. Perhaps post on julia-users for help from a Windows person? Sorry I can't be more help here, I haven't used Windows in 5-6 years, and rely on CI services to test that the unit tests run without error on Windows.

https://groups.google.com/forum/#!forum/julia-users

**Comment by randyzwitch** [comment]
Closing this out, as I'm tagging a new version at METADATA, and the Windows 64-bit testing passed, which suggests that the filename too long issue is resolved.

I also removed the PyCall dependency for 0.6.1,  which really wasn't a dependency at all (I once intended to use Python for my testing, but never did). This suggests any Conda/PyCall issues you saw above will be removed from Vega.

Good luck with this, hopefully you get everything sorted out.
